import { NextResponse } from "next/server";
import { Resend } from "resend";
import type { BSReport, SendReportRequest } from "@/lib/contracts";

if (!process.env.RESEND_API_KEY) {
  throw new Error("RESEND_API_KEY is not set");
}

const resend = new Resend(process.env.RESEND_API_KEY);

// Swap to your verified domain when DNS is ready:
// const FROM = "bs-detector@ndyhadd.ad";
const FROM = "onboarding@resend.dev";

function reportToHtml(report: BSReport, url?: string): string {
  const claimsHtml = report.claims
    .map(
      (c) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;">${c.claim}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;font-weight:600;">${c.verdict}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee;color:#666;">${c.analysis || ""}</td>
      </tr>`
    )
    .join("");

  const checksOutHtml = report.checksOut
    .map((item) => `<li style="margin-bottom:4px;">${item}</li>`)
    .join("");

  const redFlagsHtml = report.redFlags
    .map((item) => `<li style="margin-bottom:4px;color:#c0392b;">${item}</li>`)
    .join("");

  return `
    <div style="font-family:system-ui,sans-serif;max-width:700px;margin:0 auto;color:#222;">
      <h1 style="font-size:24px;border-bottom:2px solid #e74c3c;padding-bottom:8px;">
        BS Detector Report
      </h1>
      ${url ? `<p style="color:#666;font-size:14px;">Source: <a href="${url}">${url}</a></p>` : ""}

      <h2 style="font-size:18px;margin-top:24px;">Overall Assessment</h2>
      <p style="line-height:1.6;">${report.overallAssessment}</p>

      <h2 style="font-size:18px;margin-top:24px;">Claims Analysis</h2>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <tr style="background:#f5f5f5;">
          <th style="padding:8px 12px;text-align:left;">Claim</th>
          <th style="padding:8px 12px;text-align:left;">Verdict</th>
          <th style="padding:8px 12px;text-align:left;">Analysis</th>
        </tr>
        ${claimsHtml}
      </table>

      <h2 style="font-size:18px;margin-top:24px;">What Checks Out</h2>
      <ul>${checksOutHtml}</ul>

      <h2 style="font-size:18px;margin-top:24px;color:#c0392b;">Top Red Flags</h2>
      <ol>${redFlagsHtml}</ol>

      <hr style="margin-top:32px;border:none;border-top:1px solid #ddd;">
      <p style="font-size:12px;color:#999;">Generated by BS Detector</p>
    </div>
  `;
}

export async function POST(req: Request) {
  const { report, email, url }: SendReportRequest = await req.json();

  if (!report || !email) {
    return NextResponse.json(
      { error: "Missing 'report' or 'email' field" },
      { status: 400 }
    );
  }

  try {
    const { data, error } = await resend.emails.send({
      from: FROM,
      to: email,
      subject: `BS Report${url ? `: ${url}` : ""}`,
      html: reportToHtml(report, url),
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, messageId: data?.id });
  } catch (e) {
    console.error("Send report error:", e);
    return NextResponse.json(
      { success: false, error: "Failed to send email" },
      { status: 500 }
    );
  }
}
